- name: Deploy Tracking App
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Login to ECR
      shell: |
        aws ecr get-login-password | docker login --username AWS --password-stdin <ECR_URI>

    - name: Pull Docker Image
      shell: docker pull <ECR_URI>/tracking-app:latest

    - name: Run Container
      shell: |
        docker stop tracking || true && docker rm tracking || true
        docker run -d -p 3000:3000 --name tracking <ECR_URI>/tracking-app:latest
