- name: Docker 앱 배포
  hosts: app_servers
  become: yes

  tasks:
    - name: Docker 설치
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Docker 서비스 시작
      service:
        name: docker
        state: started
        enabled: true

    - name: AWS ECR 로그인
      shell: |
        aws ecr get-login-password --region ap-northeast-2 | \
        docker login --username AWS --password-stdin 122996776662.dkr.ecr.ap-northeast-2.amazonaws.com

    - name: Docker 이미지 Pull 및 실행
      shell: |
        docker stop tracking || true && docker rm tracking || true
        docker run -d -p 3000:3000 --name tracking 122996776662.dkr.ecr.ap-northeast-2.amazonaws.com/tracking-app:latest
