name: CI/CD for Real-time Tracking

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=terraform/envs/dev init

    - name: Terraform Apply
      run: terraform -chdir=terraform/envs/dev apply -auto-approve

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible sshpass

    - name: Add EC2 Host to Inventory
      run: |
        echo "[ec2]" > ansible/inventory.ini
        echo "$(terraform -chdir=terraform/envs/dev output -raw public_ip)" ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your_key.pem >> ansible/inventory.ini

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
