name: CI/CD for Real-time Tracking (Private EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2
      ECR_REPO: tracking-app

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin <your_aws_account_id>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build & Push Docker image
      run: |
        docker build -t $ECR_REPO:latest .
        docker tag $ECR_REPO:latest <your_aws_account_id>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:latest
        docker push <your_aws_account_id>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:latest
